global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'tazosploit'
    static_configs:
      - targets: ['control-plane-api:8000', 'job-scheduler:8001']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
